apiVersion: v1
kind: ServiceMonitor
metadata:
  name: lab3v-servicemonitor
  namespace: lab3v-app
  labels:
    app: lab3v
    release: prometheus
spec:
  selector:
    matchLabels:
      app: lab3v
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: mysql-servicemonitor
  namespace: lab3v-app
  labels:
    app: mysql
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mysql
  endpoints:
  - port: mysql
    interval: 30s
